version: "3.9"

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    platform: linux/amd64  
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64  
    ports:
      - "2181:2181"

  consumer_flink:
    build:
      context: .
      dockerfile: consumer_flink/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SCRIPT: consumer_flink/consumer_flink.py
      KAFKA_HOST: kafka:9092
      ZOOKEEPER_HOST: zookeeper:2181
      KAFKA_TOPIC: users
      KAFKA_CONSUMER_GROUP: Flink-Group
